; custom php.ini for Piplex Operations
extension_dir = "c:\Users\sikaa\OneDrive\Desktop\richard's intrusive platform\php\ext"

extension = pdo_sqlite
extension = sqlite3
extension = mbstring
extension = openssl

date.timezone = UTC
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
html_errors = Off
log_errors = On
; error_log = "c:\Users\sikaa\OneDrive\Desktop\richard's intrusive platform\backend\php_error.log"
post_max_size = 20M
upload_max_filesize = 20M
